name: "Update Pull Request from Branch Name"
description: "Updates a pull request with information extracted from branch name"
author: "Jamie Wright"
runs:
  using: "node16"
  main: "dist/index.js"
inputs:
  repo-token:
    description: "[REQUIRED] The GITHUB_TOKEN secret, which is needed to access the repository"
    required: true
  base-branch-regex:
    description: "Regex to match text in the base branch name"
    required: false
    default: ""
  head-branch-regex:
    description: "Regex to match text in the head branch name"
    required: false
    default: ""
  lowercase-branch:
    description: "Should make the branch name lowercase before matching"
    required: false
    default: "true"
  title-template:
    description: "Text to insert into the PR title. This is based on the matched text from `base-branch-regex` or `head-branch-regex`. You can use whatever text you like, along with the following tokens: %basebranch% | %headbranch%"
    required: false
    default: ""
  title-update-action:
    description: "Action to perform on the title. Allowed values: prefix | suffix | replace"
    required: false
    default: "prefix"
  title-insert-space:
    description: "Should the action insert a space between title and its prefix/suffix"
    required: false
    default: "true"
  title-uppercase-base-match:
    description: "Should the matched text from base branch be in the title. This is a check and will not update anything."
    required: false
    default: "true"
  title-uppercase-head-match:
    description: "Should the matched text from head branch be in the title. This is a check and will not update anything"
    required: false
    default: "true"
  body-template:
    description: "Text to insert into the PR body. This is based on the matched text from `base-branch-regex` or `head-branch-regex`. You can use whatever text you like, along with the following tokens: %basebranch% | %headbranch%"
    required: false
    default: ""
  body-update-action:
    description: "Update action to perform on the body. Allowed values: prefix | suffix | replace"
    required: false
    default: "prefix"
  body-newline-count:
    description: "Number of newlines to separate body and its prefix/suffix"
    required: false
    default: "2"
  body-uppercase-base-match:
    description: "Should the matched text from base branch be in the body. This is a check and will not change anything."
    required: false
    default: "true"
  body-uppercase-head-match:
    description: "Should the matched text from head branch be in the body. This is a check and will not change anything."
    required: false
    default: "true"
outputs:
  baseMatch:
    description: "Matched text from base branch, if any"
  headMatch:
    description: "Matched text from head branch, if any"
  titleUpdated:
    description: "Whether the PR title was updated"
  bodyUpdated:
    description: "Whether the PR body was updated"
branding:
  icon: "edit-3"
  color: "green"
