name: 'PR Update GitHub Action'
description: 'GitHub Action that updates a pull request with information extracted from branch name'
author: 'Tamim Khan'
runs:
  using: 'node12'
  main: 'index.js'
inputs:
  branch-regex:
    description: 'Regex to match branch name'
    required: true
    default: 'PROJECT-\d+'
  prefix-template:
    description: 'Title prefix template where branch info gets substituted in'
    required: true
    default: '[%branch%]'
branding:
  icon: 'edit-3'
  color: 'green'
